### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by markuznw** [oxan/hapt#4]
Hello there, I have the following error. Did i miss some steps? Does it not work anymore?

```
Wed Jul  3 00:21:16 2024 daemon.err hapt[25721]: Traceback (most recent call last):
Wed Jul  3 00:21:16 2024 daemon.err hapt[25721]:   File "/usr/bin/hapt", line 10, in <module>
Wed Jul  3 00:21:16 2024 daemon.err hapt[25721]:   File "json/__init__.py", line 114, in <module>
Wed Jul  3 00:21:16 2024 daemon.err hapt[25721]:   File "json/decoder.py", line 3, in <module>
Wed Jul  3 00:21:16 2024 daemon.err hapt[25721]:   File "/usr/lib/micropython/unix/re.py", line 6, in <module>
Wed Jul  3 00:21:16 2024 daemon.err hapt[25721]:   File "/usr/lib/micropython/unix/ffilib.py", line 38, in open
Wed Jul  3 00:21:16 2024 daemon.err hapt[25721]:   File "/usr/lib/micropython/unix/ffilib.py", line 33, in open
```

Thank you

**Comment by oxan** [comment]
This looks a lot like micropython itself is broken on your router. Is there anything before and/or after this in the logs?

**Comment by oxan** [comment]
The full error message of this issue was:
```
Traceback (most recent call last):
  File "/usr/bin/hapt", line 10, in <module>
  File "/usr/lib/micropython/unix/json/__init__.py", line 114, in <module>
  File "/usr/lib/micropython/unix/json/decoder.py", line 3, in <module>
  File "/usr/lib/micropython/unix/re.py", line 6, in <module>
  File "/usr/lib/micropython/unix/ffilib.py", line 38, in open
  File "/usr/lib/micropython/unix/ffilib.py", line 33, in open
OSError: [Errno 2] ENOENT
```

The problem being that `libpcre2-8.so`, which the `re` module required, was not present, because it required the `libpcre2` package to be installed, which was not in our dependency tree.

The switch to `ujson` in v0.5 should have fixed this.
